book_it_up/book_it_up/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.urls import re_path
from haystack.views import SearchView, search_view_factory
from haystack.query import SearchQuerySet
from haystack.forms import ModelSearchForm

sqs = SearchQuerySet()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('login/', include('login.urls')),
    path('recommendation/', include('rcm.urls')),
    path('board/', include('board.urls')),
    path('mysite/', include('mysite.urls')),
    path('book_id/', views.get_info),
    path('bestbook/',views.bestbook),
    path('about_us/', views.get_about_us),
    path('preference/',views.get_preference, name='test'),
    path('preference/getbook',views.get_book),
    path('unlogged/', views.unlogged),
    path('modify_preference/', views.modify_preference),
    path('modify_wishlist/', views.modify_wishlist),
    re_path(r'^search/', include('haystack.urls')),
    #path('search/', include('haystack.urls')),
    path('auto_complete/', views.auto_complete, name='auto_complete'),
    #path('search/',SearchView(),  name='search'),
    path('profile/',views.profile),
    path('history_register/',views.history_register, name='history_register'),
    #path('/search/history', views.search_in_history),
    path('history_register/history', views.history),
    path('history_register/history_update', views.history_update, name='history_update'),
    path('history_register/history_delete', views.history_delete, name='history_delete')

]

book_it_up/mysite/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('',views.mysite, name='mysite'),
    path('mysite_likebook/',views.mysite_likebook),
    path('mysite_wishlistbook/',views.mysite_wishlistbook),
    path('all_like/',views.all_like),
    path('all_wish/',views.all_wish),
    path('user_info/', views.user_info),
    path('mysite_update/', views.mysite_update),
    path('all_like/mysite_likebook/',views.mysite_likebook),
    path('all_wish/mysite_wishlistbook/',views.mysite_wishlistbook),
    path('usage/', views.usage),
    path('board/', views.mysite_board)
]

book_it_up/rcm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.rcm, name="rcm"),
    path('keyword', views.get_topic, name="keyword"),
    path('get_topic_rcm', views.get_topic_rcm),
    path('get_topic_refresh', views.get_topic_refresh),
]

book_it_up/book_it_up/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from haystack import indexes

# haystack searchindex 생성 :
# 1) book model과 상응하는 bookIndex생성하자 -> search_indexes.py file에 작성한다


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)

class Board(models.Model):
    board_id = models.AutoField(primary_key=True)
    user = models.ForeignKey('User', models.DO_NOTHING, blank=True, null=True)
    book_id = models.CharField(max_length=20, blank=True, null=True)
    board_content = models.TextField(blank=True, null=True)
    pubdate = models.DateField(blank=True, null=True)
    title = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'board'




class Book(models.Model):
    book_id = models.CharField(primary_key=True, max_length=20)
    title = models.TextField(blank=True, null=True)
    cover = models.TextField(blank=True, null=True)
    publisher = models.TextField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    author_id = models.CharField(max_length=20, blank=True, null=True)
    pubdate = models.DateField(blank=True, null=True)
    translator = models.TextField(blank=True, null=True)
    adult = models.IntegerField(blank=True, null=True)
    author = models.TextField(blank=True, null=True)
    category = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book'


class BookCover(models.Model):
    book = models.OneToOneField('BookDesc', models.DO_NOTHING, primary_key=True)
    cover = models.TextField(blank=True, null=True)
    cover_large = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_cover'

class BookDesc(models.Model):
    book = models.OneToOneField(Book, models.DO_NOTHING, primary_key=True)
    content = models.TextField(blank=True, null=True)
    description1 = models.TextField(blank=True, null=True)
    description2 = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_desc'

class BookDescPractice(models.Model):
    book_id = models.CharField(max_length=20)
    content = models.TextField(blank=True, null=True)
    description1 = models.TextField(blank=True, null=True)
    description2 = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_desc_practice'


class BookGrade(models.Model):
    book = models.OneToOneField(Book, models.DO_NOTHING, primary_key=True, related_name='grade')
    score = models.FloatField(blank=True, null=True)
    review_cnt = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_grade'


class BookHistory(models.Model):
    history_id = models.CharField(primary_key=True, max_length=20)
    user = models.ForeignKey('User', models.DO_NOTHING)
    book = models.ForeignKey(Book, models.DO_NOTHING, blank=True, null=True)
    score = models.FloatField(blank=True, null=True)
    start_date = models.CharField(max_length=30, blank=True, null=True)
    end_date = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_history'




class BookSize(models.Model):
    book = models.OneToOneField(BookDesc, models.DO_NOTHING, primary_key=True)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    page = models.IntegerField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_size'




class Comment(models.Model):
    comment_id = models.CharField(primary_key=True, max_length=20)
    board = models.ForeignKey(Board, models.DO_NOTHING, blank=True, null=True)
    user_id = models.CharField(max_length=20, blank=True, null=True)
    pubdate = models.DateField(blank=True, null=True)
    comment_content = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comment'


class CoverTest(models.Model):
    book_id = models.CharField(max_length=20, blank=True, null=True)
    cover_large = models.TextField(blank=True, null=True)
    cover = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'cover_test'


class DislikeTab(models.Model):
    dislike_id = models.CharField(primary_key=True, max_length=20)
    user = models.ForeignKey('User', models.DO_NOTHING, blank=True, null=True)
    book = models.ForeignKey(Book, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dislike_tab'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Isbn(models.Model):
    isbn = models.CharField(primary_key=True, max_length=10)
    isbn13 = models.CharField(max_length=14, blank=True, null=True)
    book = models.ForeignKey(Book, models.DO_NOTHING, db_column='BOOK_ID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'isbn'


class LikeTab(models.Model):
    like_id = models.CharField(primary_key=True, max_length=20)
    user = models.ForeignKey('User', models.DO_NOTHING, blank=True, null=True)
    book = models.ForeignKey(Book, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'like_tab'


class Phrase(models.Model):
    phrase_id = models.CharField(primary_key=True, max_length=20)
    phrase_content = models.TextField(blank=True, null=True)
    book = models.ForeignKey(BookDesc, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'phrase'



class Review(models.Model):
    review_id = models.CharField(primary_key=True, max_length=20)
    review_content = models.TextField(blank=True, null=True)
    book = models.ForeignKey(BookDesc, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'review'







class TestDf(models.Model):
    book_id = models.TextField(blank=True, null=True)
    cover = models.TextField(blank=True, null=True)

book_it_up/mysite/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from .models import *
import random
from pymongo import MongoClient
from django.contrib import messages
import json
from .secrets import mongo_user, mongo_pw, ip_address, port_num
from datetime import datetime
from django.utils import timezone
from datetime import datetime
from django.db.models import Avg
from haystack.views import SearchView

from haystack.generic_views import SearchView
from haystack.query import SearchQuerySet

client = MongoClient("mongodb://" + mongo_user + ":" + mongo_pw + "@" + ip_address + ":" + port_num)

# 내정보 확인하는 페이지 연결해주는 함수 :
def mysite(request):
    user_id = request.session.get('user_id')
    data={'user_id':user_id}
    return render(request,'mysite/mysite.html',data)

def mysite_likebook(request):  #mysite에서 likebook 표지들 가져오기
    user_id = request.GET.get('user_id')

    likebook = LikeTab.objects.filter(user_id=user_id).values() # user_id와 같은 user에 해당하는 데이터들을 가져와 변수에 저장

    like_lst = []
    for i in likebook:
        num = i['book_id']
        cover = BookCover.objects.filter(book_id=num).values('cover_large','book_id')[0]
        like_lst.append(cover)

    json_dict = {'books': like_lst}

    return JsonResponse(json_dict)


def mysite_wishlistbook(request): # mysite에서 wishlist 표지들 가져오기
    user_id = request.GET.get('user_id')

    wishlistbook = Wishlist.objects.filter(user_id=user_id).values() # user_id와 같은 user에 해당하는 데이터들을 가져와 변수에 저장

    wishlist_lst = []
    for i in wishlistbook:
        num = i['book_id']
        cover = BookCover.objects.filter(book_id=num).values('cover_large','book_id')[0]
        wishlist_lst.append(cover)

    json_dict = {'books': wishlist_lst}

    return JsonResponse(json_dict)


def all_like(request):
    user_id = request.session.get('user_id')

    data={'user_id':user_id}
    return render(request,'book_it_up/all_like.html',data)

def all_wish(request):
    user_id = request.session.get('user_id')
    data={'user_id':user_id}
    return render(request,'book_it_up/all_wishlist.html',data)

def user_info(request):
    user_id = request.GET.get('user_id')

    mysite_user = User.objects.filter(user_id=user_id).values()[0]
    return JsonResponse(mysite_user)

def mysite_update(request):
    user_id = request.GET.get('user_id')
    user_email = request.GET.get('email')
    gender = request.GET.get('gender')
    birth = request.GET.get('birth')


    user_update = User.objects.get(user_id=user_id)  # 유저 모델에서 user_id 일치하는 애 가져온다

    # 새로 입력한 값으로 업데이트
    user_update.user_email = user_email
    user_update.gender= gender
    user_update.birth = birth

    user_update.save()  # 해당 내용을 db에 저장

    data = {'result': '성공'}
    return JsonResponse(data)  # ajax 응답하려고 넣음


def usage(request):
    user_id = request.GET.get('user_id')
    like= LikeTab.objects.filter(user_id=user_id)
    dislike=DislikeTab.objects.filter(user_id=user_id)
    wish=Wishlist.objects.filter(user_id=user_id)
    history=BookHistory.objects.filter(user_id=user_id)

    data = {'like':len(like),'dislike':len(dislike),'total':len(like)+len(dislike),'wishlist':len(wish),'history':len(history)}
    for d in data:
        if data[d]=="undefined":
            data[d] == 0

    return JsonResponse(data)


def mysite_board(request):
    user_id = request.GET.get('user_id')
    board = Board.objects.filter(user_id=user_id).values()

    board_lst =[]
    for i in board:
        board_lst.append(i)

    data = {'board':board_lst}
    print(data)
    return JsonResponse(data)

book_it_up/book_it_up/templates/book_it_up/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="{% static 'js/error.js' %}"></script>
    <script>
    var userId = "{{ user_id }}"
    alert('20개 이상의 도서에 좋아요를 해주세요')
    location.href="/preference/?user_id=" + userId

    </script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ user_id }}
</body>
</html>

book_it_up/book_it_up/templates/book_it_up/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>main page</title>
    <link rel="icon" href="{% static 'images/bookitup_logo3.png' %}">
<!--    <link rel="icon" href="/static/www/favicon.ico">-->
    <link rel="stylesheet" href="{% static 'css/index-header.css' %}">
    <link rel="stylesheet" href="{% static 'css/index-section.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link rel="stylesheet" href="{% static 'css/book_img.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/search_auto_complete.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>

    <script type="text/javascript">
        // 외부에 js 파일에서 django 변수 접근이 불가능하기 때문에 django 변수 접근용 js는 html 내에 따로로 만들어주기
        var userId = "{{ user_id }}"
        var firstUser = "{{ user }}"
        //var likeBtnSrc = "{% static 'images/heart.png' %}"
    </script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/modal.js' %}"></script>
    <script src="{% static 'js/swiper.js' %}"></script>
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <script src="{% static 'js/search_auto_complete.js'%}"></script>

    <script src="https://kit.fontawesome.com/e0d225eaba.js" crossorigin="anonymous"></script>



    <style>

    </style>
</head>
<body>
    <header>
        <div>
            <div>
                <nav>
                    {% if user_id %}
                        <ul class="left-nav">
                            <li><img class='logo-img' src="{% static 'images/bookitup_logo3.png' %}"></li>
                            <li><a href="/">Home</a></li>
                            <li><a href="/preference?user_id={{user_id}}">Preference</a></li>
                            <li class="menu">
                                <div class="parent-menu">
                                    <a href="#">Recommendation</a>
                                </div>
                                <ul class="hide-menu">
                                    <li class="submenu"><a href="/recommendation">by preference</a></li>
                                    <li class="submenu"><a href="/recommendation/keyword">by keywords</a></li>
                                </ul>
                            </li>
                            <li><a href="/board">Community</a></li>
                            <li><a href="/about_us">AboutUs</a></li>
                        </ul>
                        <ul class="right-nav">
                            <li style="width: 170px;">
                                <form method="get" action="/search" class="autocomplete-me" style="width: 170px;">
                                    <div class="search-box">
                                        <input type="text" id="id_q" name="q" style="width: 120px; margin: 0px; font-size: 12px; height: 18px;">
                                        <input type="hidden" class="read-form-control" name="user-id" value="{{user_id}}">
<!--                                        <input type="submit" value='' class="search-submit" style="width: 30px; margin: 0px;">-->
                                        <button type="submit" value='' class="search-submit" style="width: 30px; margin: 0px;"><i class="fas fa-search"></i></button>
                                    </div>
                                </form>
                            </li>
                            <li class="menu" id='my-info'>
                                <div class="parent-menu">
                                    <a href="#">{{user_id}}</a>
                                </div>
                                <ul class="hide-menu">
                                    <li class="submenu" >
                                        <div class="card">
                                            <p id="nickname"></p>
                                        </div>
                                    </li>
                                    <li class="submenu" id="read_book"><a href="#"></a></li>
                                    <li class="submenu"><a href="{% url 'mysite' %}">My page</a></li>
                                    <li class="submenu"><a href="{% url 'history_register' %}">My Library</a></li>
                                    <li class="submenu"><a href=" {% url 'logout' %} ">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="left-nav">
                            <li><img class='logo-img' src="{% static 'images/bookitup_logo3.png' %}"></li>
                            <li><a href="/unlogged">Home</a></li>
                            <li><a href="/unlogged">Preferences</a></li>
                            <li><a href="/unlogged">Recommendation</a></li>
                            <li><a href="/unlogged">Community</a></li>
                            <li><a href="/unlogged">AboutUs</a></li>
                        </ul>
                        <ul class="right-nav">
                            <li><a href=" {% url 'index' %} ">Login/Signup</a></li>
                        </ul>
                    {% endif %}
                </nav>
            </div>
            <div id="quote-box">
                <p class="quote">
                    SO LITTLE <b>TIME,</b>
                </p>
                <p class="quote2">
                    SO MANY <b>BOOKS</b>
                </p>
            </div>
        </div>
    </header>

    <section class="page-start">
        <article id="rank-books">
            <h2>#책itUp 유저들 사이에서 핫한 책</h2>
               <ul id="rank-container">
               </ul>
         </article>
        <article id="love-books">
            <h2>#연애세포 뿜뿜일 때, #설레고 싶은 날엔</h2>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for book_set in love_books %}
                        <div class="swiper-slide">
                            {% for book in book_set %}
                                <div class="book-img-container">
                                    <img src={{ book.img_url }} name={{ book.book_id }} class="book-img">
                                    <span><i class="fas fa-heart wishlist-btn btns fa-2x" style='position: absolute; top: 85%; left: 80%; z-index: 30'></i></span>
                                    <span><i class="fas fa-thumbs-up like-btn btns fa-3x" style='position: absolute; top: 70px; left: 80px; z-index: 30'></i></span>
                                    <span><i class="fas fa-thumbs-down dislike-btn btns fa-3x" style='position: absolute; top: 160px; left: 80px; z-index: 30'></i></span>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-button-next"></div><!-- 다음 버튼 (오른쪽에 있는 버튼) -->
                <div class="swiper-button-prev"></div><!-- 이전 버튼 -->
            </div>
        </article>
        <article id="light-books" class="container" >
            <h2> #이동할 때, #시간 없을 때, #가볍게 읽기 좋은</h2>
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for book_set in short_books %}
                        <div class="swiper-slide">
                            {% for book in book_set %}
                                <div class="book-img-container">
                                    <img src={{ book.img_url }} name={{ book.book_id }} class="book-img">
                                    <span><i class="fas fa-heart wishlist-btn btns fa-2x" style='position: absolute; top: 85%; left: 80%; z-index: 30'></i></span>
                                    <span><i class="fas fa-thumbs-up like-btn btns fa-3x" style='position: absolute; top: 70px; left: 80px; z-index: 30'></i></span>
                                    <span><i class="fas fa-thumbs-down dislike-btn btns fa-3x" style='position: absolute; top: 160px; left: 80px; z-index: 30'></i></span>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-button-next"></div><!-- 다음 버튼 (오른쪽에 있는 버튼) -->
                <div class="swiper-button-prev"></div><!-- 이전 버튼 -->
            </div>
        </article>
        <article id="timely-books" class="container">
            {% if is_daytime %}
                <h2> #성공하고싶을 때, #동기부여 받고 싶을 때, #자극받기 좋은</h2>
            {% else %}
                <h2> #감수성 풍부할 때, #잠안올 때, #인생에 지칠 때</h2>
            {% endif %}
           <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% for book_set in hourly_books %}
                        <div class="swiper-slide">
                            {% for book in book_set %}
                                <div class="book-img-container">
                                    <img src={{ book.img_url }} name={{ book.book_id }} class="book-img">
                                    <span><i class="fas fa-heart wishlist-btn btns fa-2x" style='position: absolute; top: 85%; left: 80%; z-index: 30'></i></span>
                                    <span><i class="fas fa-thumbs-up like-btn btns fa-3x" style='position: absolute; top: 70px; left: 80px; z-index: 30'></i></span>
                                    <span><i class="fas fa-thumbs-down dislike-btn btns fa-3x" style='position: absolute; top: 160px; left: 80px; z-index: 30'></i></span>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-button-next"></div><!-- 다음 버튼 (오른쪽에 있는 버튼) -->
                <div class="swiper-button-prev"></div><!-- 이전 버튼 -->
            </div>
        <article>
            <div id='modal'>
                <div class="close">닫기</div>
                <div class="modal-content">
                    <div id="modal-nav">
                        <span id="modal-info-page">기본 정보</span>
                        <span id="modal-desc-page">책 소개</span>
                        <span id="modal-review-page">리뷰</span>
                        <span id="modal-quote-page">책 속 한마디</span>
                    </div>
                    <div id="top-box">
                        <div id="left-box"></div>
                        <div id="right-box"></div>
                    </div>
                    <div id="bottom-box">
                        <div id="bottom-small-box"></div>
                    </div>
                </div>
            </div>
        </article>
    </section>

    <footer id="ending">
        <div>
            <div class="Lastlogo">
                <img src="{% static 'images/bookitup_logo3.png' %}" alt="">
            </div>

            <div class="endlst">
                <ul id="main-set">
                    <li>
                        <span>Main</span>
                        <a href="/">Home</a>
                    </li>
                </ul>
                <ul id="recommendation-set">
                    <li>
                        <span>Recommendation</span>
                        <a href="/recommendation">by preference</a>
                        <a href="/recommendation/keyword">by keyword</a>
                    </li>
                </ul>
                <ul id="community-set">
                    <li>
                        <span>Community</span>
                        <a href="/board">Community</a>
                        <a href="/about_us">About Us</a>
                    </li>
                </ul>
            </div>
            <div id="introduction">
            <a href="#">오벤져스</a>
            <a href="#">홍지수, 조성헌, 임지윤, 홍동수, 조원제</a>
            <span>책itUp</span>
        </div>
        </div>
    </footer>

</body>
</html>

book_it_up/book_it_up/templates/book_it_up/unlogged.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Unlogged</title>
    <link rel="icon" href="{% static 'images/bookitup_logo3.png' %}">
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="{% static 'js/unlogged.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

    <style>
        .regi{
            text-align: center;

        }
        a{
            display: inline-block;
            font-size: 30pt;
            padding: 70px;
        }

        a:hover{
            transform: scale(1.05);
        }
    </style>
</head>
<body>
<div class="background">
        <div class="background-shadow">
            <div class="container">
                <div class="row">
                    <div class="regi">
                        <a href="/login">로그인 페이지로 이동하기</a>
                        <br>
                        <a href="/">홈페이지로 돌아가기</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>
</html>